name: Build and Test (Branch)

on:
  push:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        matplotlib-version: ['>=3.6']

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict
        show-channel-urls: true
        miniforge-version: latest
        miniforge-variant: Mambaforge

    - name: Configure conda and install code
      shell: bash -l {0}
      run: |
        mamba config --set always_yes yes
        mamba install numpy "astropy>=4.0" "matplotlib${{ matrix.matplotlib-version }}" hpgeom setuptools_scm setuptools_scm_git_archive healsparse "pyproj>=3.1" flake8 pytest jupyter "nbconvert<7"
        python -m pip install --no-deps .

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if it fails flake8 with default setup.cfg
        flake8 . --count --show-source --statistics
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest
